%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/natalia/MA-Gesture-Recognition/Recorded Data/labelledData.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2014/05/13 16:15:54

%% Initialize variables.
filename = '/Users/natalia/MA-Gesture-Recognition/Recorded Data/labelledData.csv';
delimiter = ',';
endRow = 268;

%% Format string for each line of text:
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*s%*s%*s%*s%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow, 'Delimiter', delimiter, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
VarName5 = dataArray{:, 1};
VarName6 = dataArray{:, 2};
VarName7 = dataArray{:, 3};

%% Clear temporary variables
clearvars filename delimiter endRow formatSpec fileID dataArray ans;